### ISSUE TITLE
JSON deserialization issue starting from `0.3.3`

### ISSUE THREAD

**Issue by eric-carlsson** [microsoft/kiota-serialization-json-python#83]
#### Description

Starting from version `0.3.3`, `JsonParseNode._assign_field_values` throws an attribute error since this value:

https://github.com/microsoft/kiota-serialization-json-python/blob/da130088a3aa4ceac27a3a5543d9936bad92a6ae/kiota_serialization_json/json_parse_node.py#L274

Is expected to be a dict, but is in fact a (non-deserialized) json string. 

This will cause issues when using packages that depend on this package to do JSON deserialization. For example, using the `msgraph-sdk` we may get an error like:

```
  File "...", line 15, in _get_me
    user = await self.api.me.get()
  File ".../lib/python3.8/site-packages/msgraph/generated/me/me_request_builder.py", line 143, in get
    return await self.request_adapter.send_async(request_info, user.User, error_mapping)
  File ".../lib/python3.8/site-packages/kiota_http/httpx_request_adapter.py", line 122, in send_async
    result = root_node.get_object_value(model_type)
  File ".../lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 227, in get_object_value
    self._assign_field_values(result)
  File ".../lib/python3.8/site-packages/kiota_serialization_json/json_parse_node.py", line 287, in _assign_field_values
    for key, val in object_dict.items():
AttributeError: 'str' object has no attribute 'items'
```

This is only an issue in 0.3.3 afaict, downgrading to 0.3.2 seems to solve the issue. My immediate idea is that this might be related to changes in https://github.com/microsoft/kiota-serialization-json-python/commit/0158e77b005076f5adb0a8c0a2ba48807f9364b5?

**Comment by chuushi** [comment]
I was running myself up on [this Microsoft tutorial on using Microsoft Graph](https://learn.microsoft.com/en-us/graph/tutorials/python?tabs=aad&tutorial-step=4) and ran into the same exact error. `_json_node` is being treated as a string. Thanks!

**Comment by PrzemyslawSagalo** [comment]
I experienced a problem with the same package version, but after making the necessary downgrade to version 0.3.2, the issue was successfully resolved.

**Comment by samwelkanda** [comment]
Closing as this was resolved
